version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install serverless
  build:
    commands:
      - ./node_modules/.bin/serverless deploy --stage dev -v | tee deploy.ou
      - mkdir artifacts
      # create staging deployment package
      - mkdir artifacts/stg
      - ./node_modules/.bin/serverless package --package artifacts/stg --stage stg -v
      # create prod deployment package
      - mkdir artifacts/prod
      - ./node_modules/.bin/serverless package --package artifacts/prod --stage prod -v
